# Generated by Django 4.1.1 on 2022-09-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=64, primary_key=b'I01\n', serialize=False)),
                ('course_name', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=64)),
                ('year', models.CharField(max_length=64)),
                ('seat', models.IntegerField(default=0)),
                ('current_seat', models.IntegerField(default=0)),
                ('q_status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=64, primary_key=b'I01\n', serialize=False)),
                ('student_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_complete', to='registers.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_complete', to='registers.student')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_apply', to='registers.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_apply', to='registers.student')),
            ],
        ),
    ]
